plugins {
    id 'com.android.application'
}

android {
    namespace 'com.ldd.c15gameboost'
    compileSdk 35

    defaultConfig {
        applicationId 'com.ldd.c15gameboost'
        minSdk 24
        targetSdk 28
        versionCode 1
        versionName '1.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
        coreLibraryDesugaringEnabled true
    }
}

dependencies {
    def shizuku_version = '13.1.5'
    implementation "dev.rikka.shizuku:api:$shizuku_version"
    implementation "dev.rikka.shizuku:provider:$shizuku_version"
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.1.3'
}
